---
- name: Satellite server configuration playbook
  hosts: ipaserver,ipaclients
  become: true
  vars_prompt:
    - name: rhsm_user
      prompt: What is your RHSM Username (RHNID)?
      unsafe: yes
      private: no

    - name: rhsm_password
      prompt: What is your RHSM Password?
      unsafe: yes
      private: yes

#    - name: rhsm_pool_id
#      prompt: What is the pool-id for your subscription (check README)?
#      unsafe: yes
#      private: no

  tasks:
    - name: Register system with Red Hat Subscription Manager
      community.general.redhat_subscription:
        state: present
        username: "{{ rhsm_user }}"
        password: "{{ rhsm_password }}"
#        pool_ids: "{{ rhsm_pool_id }}"

    - name: Ensure all packages are updated
      yum:
        name: '*'
        state: latest

- name: Playbook to configure IPA servers
  hosts: ipaserver
  become: true
  collections:
    - freeipa.ansible_freeipa

  roles:
  - role: freeipa.ansible_freeipa.ipaserver
    state: present

- name: Playbook to configure IPA clients with username/password
  hosts: ipaclients
  become: true
  collections:
    - freeipa.ansible_freeipa
  roles:
  - role: freeipa.ansible_freeipa.ipaclient
    state: present
