- name: This play provisions loadbalancer VM for control plane
  hosts: localhost
  vars:
    domain: rhdemo.labs
    network_cidr: "[192.168.215.0/24]"
 
  tasks:
    - name: Provision all terraform resources
      community.general.terraform:
        project_path: "terraform"
        force_init: true
        variables:
          network_cidr: "{{ network_cidr }}"
          domain: "{{ domain }}"
        state: present
      become: true

    - name: Add servers to inventory
      add_host:
        hostname: "{{ item }}.{{ domain }}"
        ansible_user: sysadmin
        ansible_password: redhat
        groups:
          - "servers"        
      loop:
        - centos-server
        - rhel-server

    - name: Ensure to clean known_hosts
      known_hosts:
        host: "{{ item }}"
        path: ~/.ssh/known_hosts
        state: absent
      loop: "{{ groups['servers'] }}"
      become: true

- name: Check connection to loadbalancer
  hosts: servers
  gather_facts: no
  tasks:
    - name: Wait 600 seconds for target connection to become reachable/usable
      wait_for_connection:
        timeout: 600
        delay: 0

    - ping:

    - name: Extract facts from setup
      setup:
      register: lb_facts

    - set_fact:
        host_ip: "{{ lb_facts.ansible_facts.ansible_default_ipv4.address }}"
        host_interface: "{{ lb_facts.ansible_facts.ansible_default_ipv4.interface }}"
        host_mac: "{{ lb_facts.ansible_facts.ansible_default_ipv4.macaddress }}"
        host_fqdn: "{{ lb_facts.ansible_facts.ansible_fqdn }}"

